### ISSUE TITLE
Migrations not working w/ Django 1.6.11

### ISSUE THREAD

**Issue by sgtsquiggs** [django-silk/silk#101]
``` shell
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/migration/__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/migration/base.py", line 229, in calculate_dependencies
    migration.calculate_dependencies()
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/migration/base.py", line 363, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/migration/base.py", line 343, in _get_dependency_objects
    for app, name in getattr(self.migration_class(), attrname, []):
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/migration/base.py", line 315, in migration_class
    return self.migration().Migration
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/migration/base.py", line 304, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'silk:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/Users/matthew/.virtualenvs/nauman/lib/python2.7/site-packages/silk/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

The solution from https://github.com/django-silk/silk/issues/64 did not fix this.

**Comment by avelis** [comment]
It would appear that the error is trying to load Django migrations and not south_migrations. Django migrations are not available in Django 1.6.+.

**Comment by avelis** [comment]
@sgtsquiggs Just to be thorough do you have the settings set for south migrations:
```python
SOUTH_MIGRATION_MODULES = {
    'silk': 'silk.south_migrations',
}
```
As commented by @pbassut in #64 ?

**Comment by sgtsquiggs** [comment]
@avelis:

```
Running migrations for silk:
- Nothing to migrate.
 - Loading initial data for silk.
Installed 0 object(s) from 0 fixture(s)
```

yet `ProgrammingError: (1146, "Table 'devdb.nauman_silk_request' doesn't exist")` error when visiting localhost:8000/silk/

**Comment by avelis** [comment]
@sgtsquiggs Check your migrations table to see if it's in there already. It might have written in the migration to it even though it was previously using the wrong file that was causing the error you see above. It's a sanity check ask for good measure.

If it's in there you might have to rollback or remove the record in order to run the migration file again.

**Comment by markeroon** [comment]
I'm running into the same issue, and I didn't have a previous install.

I installed using `manage.py schemamigration silk --auto` and `manage.py migrate silk` without success. Any ideas?

```
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 229, in calculate_dependencies
    migration.calculate_dependencies()
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 363, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 343, in _get_dependency_objects
    for app, name in getattr(self.migration_class(), attrname, []):
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 315, in migration_class
    return self.migration().Migration
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 304, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'silk:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/silk/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

**Comment by markeroon** [comment]
Btw, setting SOUTH_MIGRATION_MODULES as above didn't help.

**Comment by sgtsquiggs** [comment]
@avelis no row in the migrations table for silk

**Comment by avelis** [comment]
@sgtsquiggs @markeroon What version of South are you using?

**Comment by sgtsquiggs** [comment]
@avelis 0.8.4

**Comment by avelis** [comment]
@sgtsquiggs The `SOUTH_MIGRATION_MODULES` will only work with South version 1.0 or newer.

It's a little hidden https://github.com/django-silk/silk/issues/64#issuecomment-93267323 I bolded it to make it more visible.

That was the solution that was ultimately decided upon in #64

**Comment by sgtsquiggs** [comment]
Ok! Now we're getting somewhere.

I retried the migration and it looks like it does take place with 0.8.4, but it does not prefix the tables with my project name (nauman).

I have 5 tables (`silk_profile`, `silk_profile_queries`, `silk_request`, `silk_response`, `silk_sqlquery`) but the /silk/ endpoint is looking for `nauman_silk_request` for example.

**Comment by markeroon** [comment]
@avelis Thanks! Upgrading South helped, but I'm still getting an Error:
```

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_class = import_by_path(middleware_path)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 26, in import_by_path
    sys.exc_info()[2])
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 21, in import_by_path
    module = import_module(module_path)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/silk/middleware.py", line 31, in <module>
    fpath = silky_reverse('summary')
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/silk/middleware.py", line 22, in silky_reverse
    r = reverse('silk:%s' % name, *args, **kwargs)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 480, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 310, in app_dict
    self._populate()
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 262, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/src/adalytics/adalytics/adalytics/urls.py", line 24, in <module>
    url(r'^profiler/', include('profiler.urls')),
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/src/adalytics/.venv/local/lib/python2.7/site-packages/profiler/urls.py", line 1, in <module>
    from django.conf.urls.defaults import *
ImproperlyConfigured: Error importing module silk.middleware: "No module named defaults"
```

**Comment by avelis** [comment]
@sgtsquiggs Looking at your stacktrace I am not sure why the ORM is looking for a table that doesn't exist. I would honestly try a fresh migration. Ensure that all tables and all south_migration records are cleared out before trying again.

**Comment by avelis** [comment]
@markeroon Given the nature of your stacktrace I am honestly perplexed as to what is causing it. Trying to connect the dots and I can see that someone tried to make a pull request to address something similar to it: https://github.com/django-silk/silk/pull/86

When pressing on the contributor as to the nature of the issue I didn't get much of a response.

I also a little at a loss as to the nature of your error as well.

**Comment by markeroon** [comment]
@avelis Ok. I appreciate you looking into that for me. Thanks!

**Comment by auvipy** [comment]
better to upgrade the project to django 1.8 :)

**Comment by auvipy** [comment]
@avelis I believe we could close this issue.
